apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-smoke-test.fullname" . }}
  labels:
    {{- include "k8s-smoke-test.deployment.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "k8s-smoke-test.deployment.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.deployment.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "k8s-smoke-test.deployment.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "k8s-smoke-test.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.deployment.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          args:
          - --statefulset-url=http://{{ include "k8s-smoke-test.fullname" . }}-0.{{ include "k8s-smoke-test.fullname" . }}-statefulset:8080/health
          securityContext:
            {{- toYaml .Values.deployment.securityContext | nindent 12 }}
          image: "{{ .Values.deployment.image.registry | default .Values.image.registry }}/{{ .Values.deployment.image.repository | default .Values.image.repository }}:{{ .Values.deployment.image.tag | default .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
          volumeMounts:
          - name: rwx
            mountPath: /var/lib/k8s-smoke-test/rwx
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: rwx
        persistentVolumeClaim:
          claimName: {{ include "k8s-smoke-test.fullname" . }}-rwx
