{{- $fullName := include "k8s-smoke-test.fullname" . -}}
{{- $svcPort := .Values.deployment.service.port -}}
{{- if and .Values.deployment.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.deployment.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.deployment.ingress.annotations "kubernetes.io/ingress.class" .Values.deployment.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "k8s-smoke-test.labels" . | nindent 4 }}
  {{- with .Values.deployment.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.deployment.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.deployment.ingress.className }}
  {{- end }}
  {{- if .Values.deployment.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        - {{ $.Values.deployment.ingress.hostname }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  - host: {{ .Values.deployment.ingress.hostname }}
    http:
      paths:
      - path: /
        {{- if  (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
        pathType: Prefix
        {{- end }}
        backend:
          {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
          service:
            name: {{ $fullName }}-deployment
            port:
              number: {{ $svcPort }}
          {{- else }}
          serviceName: {{ $fullName }}-deployment
          servicePort: {{ $svcPort }}
          {{- end }}
