apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-smoke-test.fullname" . }}-deployment
  labels:
    {{- include "k8s-smoke-test.deployment.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.deployment.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "k8s-smoke-test.deployment.selectorLabels" . | nindent 4 }}
