apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "k8s-smoke-test.fullname" . }}-rwx
  labels:
    {{- include "k8s-smoke-test.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep

spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.persistence.rwx.size }}
  storageClassName: {{ .Values.persistence.rwx.storageClassName }}
